config/routes.rb
Mykomiks::Application.routes.draw do |map|
  resources :categories

  resources :responses

  resources :strips do
    resources :comments
  end

  resources :comments

  match "kontakt" => "responses#new", :as => :kontakt

  root :to => "strips#index"

end

app/models/strip.rb
class Strip < ActiveRecord::Base
  has_many :comments
  has_and_belongs_to_many :categories
end

app/controllers/strips_controller.rb
class StripsController < ApplicationController
  before_filter :authenticate, :except => [:index, :show]
  before_filter :normalize, :only => [:update]

  # GET /strips
  # GET /strips.xml
  def index
    @site_desc = "This comic (komik) series created by Manish Wadhwa (aka M or Dr.M) is the komik with a 'K'. The komik of Me, You and the big 'K' of life. Now what's the big 'K', that's a mystery."
    @strips = Strip.order("id ASC").all
    @lstrips = @strips.reverse.shift(10)
    @strip = Strip.last

    @prev = @strips[(@strips.index(@strip) - 1)]
    @next = @strips.last
    @rand = @strips[rand(@strips.length)]
    unless @strips[(@strips.index(@next) + 4)].nil?
      @ff = @strips[(@strips.index(@next) + 4)]
    else
      @ff = @strips.last
    end
    unless @strips[(@strips.index(@prev) - 4)].nil?
      @fr = @strips[(@strips.index(@prev) - 4)]
    else
      @fr = @strips.first
    end

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @strips }
      format.rss
    end
  end

  # GET /strips/1
  # GET /strips/1.xml
  def show
    @strips = Strip.order("id ASC").all
    @strip = Strip.find(params[:id])
    @site_desc = @strip.story.gsub(/\n/, '').gsub(/\r/, '')

    @prev = @strips[(@strips.index(@strip) - 1)]
    @next = @strips[(@strips.index(@strip) + 1)] || @strips.last
    @rand = @strips[rand(@strips.length)]
    unless @strips[(@strips.index(@next) + 4)].nil?
      @ff = @strips[(@strips.index(@next) + 4)]
    else
      @ff = @strips.last
    end
    unless @strips[(@strips.index(@prev) - 4)].nil?
      @fr = @strips[(@strips.index(@prev) - 4)]
    else
      @fr = @strips.first
    end

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @strip }
    end
  end

  # GET /strips/new
  # GET /strips/new.xml
  def new
    @strip = Strip.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @strip }
    end
  end

  # GET /strips/1/edit
  def edit
    @strip = Strip.find(params[:id])
  end

  # POST /strips
  # POST /strips.xml
  def create
    @strip = Strip.new(params[:strip])

    respond_to do |format|
      if @strip.save
        format.html { redirect_to(@strip, :notice => 'Strip was successfully created.') }
        format.xml  { render :xml => @strip, :status => :created, :location => @strip }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @strip.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /strips/1
  # PUT /strips/1.xml
  def update
    @strip = Strip.find(params[:id])

    respond_to do |format|
      if @strip.update_attributes(params[:strip])
        format.html { redirect_to(@strip, :notice => 'Strip was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @strip.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /strips/1
  # DELETE /strips/1.xml
  def destroy
    @strip = Strip.find(params[:id])
    @strip.destroy

    respond_to do |format|
      format.html { redirect_to(strips_url) }
      format.xml  { head :ok }
    end
  end

  private
  
  def normalize
    params[:strip][:category_ids] = [1,3]
  end
end

app/helpers/strips_helper.rb
module StripsHelper
end

app/views/strips/_form.html.erb
<% form_for(@strip) do |f| %>
  <%= f.error_messages %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :url %><br />
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :story %><br />
    <%= f.text_area :story %>
  </div>
  <div class="field">
    <%= f.label :note %><br />
    <%= f.text_area :note, :rows => 6 %>
  </div>
  <h3>Categories:</h3>
  <% for category in Category.all %>
  <div>
    <%= check_box_tag "strip[category_ids][]", category.id, @strip.categories.include?(category), :id => nil %>
    <%= category.title %>
  </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/strips/_strip.html.erb
<div id="buttons">
<img id="im1" src="http://dl.dropbox.com/u/3426859/mykomiks/home/buttons-gray.gif" usemap="#im1" border="0" width="325" height="44" alt="" />
<map id="_im1" name="im1">
<area shape="rect" coords="0,0,58,39" href="/strips/<%= @fr.id %>" alt="Fast Rewind" title="Fast Rewind" />
<area shape="rect" coords="67,0,125,39" href="/strips/<%= @prev.id %>" alt="Previous" title="Previous" />
<area shape="rect" coords="133,0,191,39" href="/strips/<%= @rand.id %>" alt="Random" title="Random" />
<area shape="rect" coords="200,0,258,39" href="/strips/<%= @next.id %>" alt="Next" title="Next" />
<area shape="rect" coords="267,0,320,39" href="/strips/<%= @ff.id %>" alt="Fast Forward" title="Fast Forward" />
</map>
</div>

<div id="content">
<h2 class="img-title"><%= @strip.title %></h2>

<center>
<img src="http://dl.dropbox.com/u/3426859/mykomiks/<%= @strip.url %>.gif" alt="<%= @strip.title %>" />
</center>

<% unless @strip.note.blank? %>
<div id="note">
<%= raw simple_format(@strip.note) %>
</div>
<% end %>

<p style="display:none">
  <%= @strip.story %>
</p>

</div>

<div id="nav"><%= link_to raw('<span>&lt; Prev</span>'), @prev %> &nbsp; <%= link_to raw('<span>Next &gt;</span>'), @next %></div>

<div id="comment_section" style="padding:0 10px;border:1px solid #666; background: #ddd;">
<h3>Comments</h3>
<div id="comments">
<%= render :partial => @strip.comments.order("id ASC") %>
</div>
<!--
<hr />
<div id="comment_form">
<% form_for [@strip, @strip.comments.build] do |f| %>
  <%= f.error_messages %>

  <div class="field">
    <%= f.label :author %>* :
    <%= f.text_field :author %>
  </div>
  <div class="field">
    <%= f.label :email %>* :
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :website %> :
    <%= f.text_field :website %>
  </div>
  <div class="field">
    <%= f.label :body, "Your thoughts* :" %><br />
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit "Post Comment" %>
  </div>
  <br />
<% end %>
</div>
-->
</div>

app/views/strips/edit.html.erb
<h1>Editing strip</h1>

<%= render 'form' %>

<%= link_to 'Show', @strip %> |
<%= link_to 'Back', strips_path %>

app/views/strips/index.html.erb
<%= render :partial => 'strip' %>

app/views/strips/new.html.erb
<h1>New strip</h1>

<%= render 'form' %>

<%= link_to 'Back', strips_path %>

app/views/strips/show.html.erb
<%= render :partial => 'strip' %>