config/routes.rb
Mykomiks::Application.routes.draw do |map|
  resources :categories

  resources :responses

  resources :strips do
    resources :comments
  end

  resources :comments

  match "kontakt" => "responses#new", :as => :kontakt

  root :to => "strips#index"

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :strip
  validates_presence_of :author, :email, :body
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_filter :authenticate, :except => [:create]

  # GET /comments
  # GET /comments.xml
  def index
    @comments = Comment.order("id DESC")

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @comments }
    end
  end

  # GET /comments/1
  # GET /comments/1.xml
  def show
    @comment = Comment.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @comment }
    end
  end

  # GET /comments/new
  # GET /comments/new.xml
  def new
    @comment = Comment.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @comment }
    end
  end

  # GET /comments/1/edit
  def edit
    @comment = Comment.find(params[:id])
  end

  # POST /comments
  # POST /comments.xml
  def create
    @strip = Strip.find(params[:strip_id])
    unless ["195.55.130.44", "196.38.43.185", "208.73.177.89", "168.216.38.209", "82.127.120.116", "72.3.253.204", "143.167.8.123", "173.61.110.35", "12.168.203.132", "208.73.177.89", "91.212.226.3", "111.160.70.139", "111.160.68.12", "94.56.0.211", "195.134.102.37", "74.7.131.97"].index(request.remote_ip)
      #@comment = @strip.comments.create(params[:comment])
    end
    redirect_to strip_path(@strip) 

#    respond_to do |format|
#      if @comment.save
#        format.html { redirect_to(@comment, :notice => 'Comment was successfully created.') }
#        format.xml  { render :xml => @comment, :status => :created, :location => @comment }
#      else
#        format.html { render :action => "new" }
#        format.xml  { render :xml => @comment.errors, :status => :unprocessable_entity }
#      end
#    end
  end

  # PUT /comments/1
  # PUT /comments/1.xml
  def update
    @comment = Comment.find(params[:id])

    respond_to do |format|
      if @comment.update_attributes(params[:comment])
        format.html { redirect_to(@comment, :notice => 'Comment was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @comment.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.xml
  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy

    respond_to do |format|
      format.html { redirect_to(comments_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<% div_for comment do %>
  <p>
    By: <strong><%= (comment.website.blank?) ? comment.author : link_to(comment.author, comment.website) %></strong> <%= time_ago_in_words(comment.created_at) %> ago<br />
    <%= comment.body %>
  </p>
<% end %>

app/views/comments/_form.html.erb
<% form_for(@comment) do |f| %>
  <%= f.error_messages %>

  <div class="field">
    <%= f.label :author %><br />
    <%= f.text_field :author %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :website %><br />
    <%= f.text_field :website %>
  </div>
  <div class="field">
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </div>
  <div class="field">
    <%= f.label :approved %><br />
    <%= f.check_box :approved %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<h1>Listing comments</h1>

<table>
  <tr>
    <th>Strip</th>
    <th>Author</th>
    <th>Email</th>
    <th>Website</th>
    <th>Body</th>
    <th>Approved</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @comments.each do |comment| %>
  <tr>
    <td><%= comment.strip_id %></td>
    <td><%= comment.author %></td>
    <td><%= comment.email %></td>
    <td><%= comment.website %></td>
    <td><%= comment.body %></td>
    <td><%= comment.approved %></td>
    <td><%= link_to 'Show', comment %></td>
    <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
    <td><%= link_to 'Destroy', comment, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New comment</h1>

<%= render 'form' %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p>
  <b>Strip:</b>
  <%= @comment.strip_id %>
</p>

<p>
  <b>Author:</b>
  <%= @comment.author %>
</p>

<p>
  <b>Email:</b>
  <%= @comment.email %>
</p>

<p>
  <b>Website:</b>
  <%= @comment.website %>
</p>

<p>
  <b>Body:</b>
  <%= @comment.body %>
</p>

<p>
  <b>Approved:</b>
  <%= @comment.approved %>
</p>


<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>