config/routes.rb
Mykomiks::Application.routes.draw do |map|
  resources :categories

  resources :responses

  resources :strips do
    resources :comments
  end

  resources :comments

  match "kontakt" => "responses#new", :as => :kontakt

  root :to => "strips#index"

end

app/controllers/responses_controller.rb
class ResponsesController < ApplicationController
  # GET /responses
  # GET /responses.xml
  def index
    @responses = Response.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @responses }
    end
  end

  # GET /responses/1
  # GET /responses/1.xml
  def show
    @response = Response.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @response }
    end
  end

  # GET /responses/new
  # GET /responses/new.xml
  def new
    @response = Response.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @response }
    end
  end

  # GET /responses/1/edit
  def edit
    @response = Response.find(params[:id])
  end

  # POST /responses
  # POST /responses.xml
  def create
    @response = Response.new(params[:response])

    respond_to do |format|
      if @response.save
        format.html { redirect_to(@response, :notice => 'Response was successfully created.') }
        format.xml  { render :xml => @response, :status => :created, :location => @response }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @response.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /responses/1
  # PUT /responses/1.xml
  def update
    @response = Response.find(params[:id])

    respond_to do |format|
      if @response.update_attributes(params[:response])
        format.html { redirect_to(@response, :notice => 'Response was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @response.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /responses/1
  # DELETE /responses/1.xml
  def destroy
    @response = Response.find(params[:id])
    @response.destroy

    respond_to do |format|
      format.html { redirect_to(responses_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/responses_helper.rb
module ResponsesHelper
end

app/views/responses/_form.html.erb
<center>
<br />
<% form_for(@response) do |f| %>
  <%= f.error_messages %>
  <div class="field">
    <%= f.label :name, "Name*" %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email, "Email <i>(*wanna hear from us?)</i>" %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :phone %><br />
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :subject %>
    <%= f.select :subject, [["Komment", "comment"], ["Suggestion", "suggestion"], ["Issue", "issue"], ["Kopyright", "copyright"], ["Other", "other"]] %>
  </div>
  <div class="field">
    <%= f.text_area :comment, :rows => 10, :cols => 35 %>
  </div>
  <div class="actions">
    <%= f.submit "Submit" %>
  </div>
<% end %>
</center>

app/views/responses/edit.html.erb
<h1>Editing response</h1>

<%= render 'form' %>

<%= link_to 'Show', @response %> |
<%= link_to 'Back', responses_path %>

app/views/responses/index.html.erb
<h1>Listing responses</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th>Phone</th>
    <th>Subject</th>
    <th>Comment</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @responses.each do |response| %>
  <tr>
    <td><%= response.name %></td>
    <td><%= response.email %></td>
    <td><%= response.phone %></td>
    <td><%= response.subject %></td>
    <td><%= response.comment %></td>
    <td><%= link_to 'Show', response %></td>
    <td><%= link_to 'Edit', edit_response_path(response) %></td>
    <td><%= link_to 'Destroy', response, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New response', new_response_path %>

app/views/responses/new.html.erb
<div id="content-body">

<h2 class="img-title">Kontakt</h2>

<%= render 'form' %>

app/views/responses/show.html.erb
<p>
  <b>Name:</b>
  <%= @response.name %>
</p>

<p>
  <b>Email:</b>
  <%= @response.email %>
</p>

<p>
  <b>Phone:</b>
  <%= @response.phone %>
</p>

<p>
  <b>Subject:</b>
  <%= @response.subject %>
</p>

<p>
  <b>Comment:</b>
  <%= @response.comment %>
</p>


<%= link_to 'Edit', edit_response_path(@response) %> |
<%= link_to 'Back', responses_path %>